### ISSUE TITLE
Case sensitivity issues...

### ISSUE THREAD

**Issue by binarypaladin** [jm81/ach#31]
We're currently using this library to generate NACHA files for some internal payment processing and it works well. However, we recently ran into an odd quirk with on specific bank: company name in the batch header is case sensitive!

I monkey-patched out version so :company_name is the only field that isn't converted to uppercase, but the solution isn't ideal. I'm fine adding a patch for this if you'd prefer, but I wanted to report it first as a matter of making the quirk known.

Want me to patch this?

**Comment by jm81** [comment]
I think if you patch it (which would be great), it should still default to being upcased, maybe with a config option to change it. If I remember correctly, the bank I originally set this up for required the company_name to be uppercase. Thanks for reporting it.

**Comment by binarypaladin** [comment]
I'm amazed that there is actually a case sensitivity issue at all. I've never seen a NACHA example in anything but all uppercase.

I'll get the patch to you in a few days. As you can tell by the late reply, I'm not exactly on top of this just yet. Haha. The monkey patch is working.
