### ISSUE TITLE
file_id_modifier default value vs validation

### ISSUE THREAD

**Issue by gmhawash** [jm81/ach#36]
In `file_header.rb`, File ID Modifier has a default value of 'A', and a validation regex.  In the `file_identifier.rb`, the setter performs validation on the provided file ID modifier and does not consider the default value.  In my case, I provided a `nil` for file ID modifier thinking that it should be set to the default, but rather, an error was raised that the value does not validate against the regex.

What's the purpose of the default value when used with a validation regex?

**Comment by jm81** [comment]
Right now, the default value works only if you never try to set the value. I agree that the library should use the default value if provided nil and will get that fixed.

**Comment by gmhawash** [comment]
Thanks.
