### ISSUE TITLE
Next business day as Tuesday on weekends

### ISSUE THREAD

**Issue by terencedignon** [jm81/ach#38]
Could you explain why ACH returns Tuesday as the next business day for Fri-Sun? That's been a recurring issue for us.  Thanks for all your work.

**Comment by aripollak** [comment]
@terencedignon this is based on a single data point, which is that the bank I was using had these rules:

> the effective date of an ACH batch must be the next business day, or if today is not a business day, then the business day after that. 

That seemed to make sense to me given that processing doesn't happen Sat-Sun, but it does on Monday, and the next business day after that is Tuesday.

**Comment by dlionikis** [comment]
There are a number of banks that process files on Sunday evening and allow for Monday effective dates when submitting files on Friday evening or the weekend.  This logic is always bank-specific, with cut-off times and processing schedules for weekends and holidays vary greatly.  Currently I'm working with 3 different banks that all handle this differently.

**Comment by terencedignon** [comment]
@aripollak @dlionikis Thanks for the answers.  I wasn't sure if I was missing something, since I'm working with a single data point that operates on a different schedule.
