### ISSUE TITLE
batch_number does not increment with successive batches?

### ISSUE THREAD

**Issue by zhoujeffrey** [jm81/ach#42]
I might be the issue here, but wanted to raise as I couldn't find any call in the code setting batch_number in the header

**Comment by jm81** [comment]
Yes, you're right, it doesn't auto-increment. I'll work on adding that (I've only ever done single batch files so never noticed that I forgot to add that functionality). The only way to achieve incremented batch numbers right now is to set the batch_number when setting up the batch header (bh.batch_number = 2).

**Comment by jm81** [comment]
After looking at the code a bit more, I saw a pretty easy way to add incrementing support, so I've done that and released version 0.5.4 . If you have any feedback, please let me know. Thanks
