### ISSUE TITLE
Holidays versioning

### ISSUE THREAD

**Issue by destinf** [jm81/ach#50]
Hi, I've been doing some digging and I have a couple of questions the versioning of the holidays gem in `ach.gemspec`.
`s.add_runtime_dependency('holidays', '>= 1.2.0', '< 5.4.0')`

1. Do versions above `5.4.0` affect this code in unexpected ways?
1. It seems like quite a range of versions, is there a need to support this range? (I ask because I see that TravisCI is failing on holiday gem 3.0.0)

Thank you in advance!

**Comment by jm81** [comment]
I was also wondering about this after noticing the same TravisCI failure and have meant to look into it. I think the max version was just based on the versions available at the time the dependency was added. My gut feeling is to try to allow anything >= 3.1.0 but I just haven't taken the time yet to dig into it.

**Comment by destinf** [comment]
Hi @jm81, thank you for the response! I've done a bit of digging myself and it looks like holidays past version 7.0 have a change that break the `federal_reserve` feature used here. (Looks like it's been renamed to `federalreserve`). I am writing a branch that handles holidays >= 3.1, do you think that would be a valuable PR to create for this repo?

**Comment by jm81** [comment]
Yes, a PR for that would be great if you'd like to work on it. I also just pulled in a PR #52 which adds some support for some versions, so that might already take care of much of it.
